### ISSUE TITLE
Info: maybe some pointers of help

### ISSUE THREAD

**Issue by malc0mn** [fujihack/fujihack#12]
First of all, extremely cool project this! I've been reverse engineering the PTP/IP protocol used by my Fuji X-T1 camera during the first Covid19 lockdown period which is open sourced here: https://github.com/malc0mn/ptp-ip

The Fuji specific stuff is in this file: https://github.com/malc0mn/ptp-ip/blob/master/ip/packets_fuji.go. The key to make the camera accept my custom client can be found on line 219 in the constant `PV_Fuji`. I do not know if this is an X-T1 specific thing, it most likely is, but maybe some other constants from that file can help you identify the functionality of parts of the firmware.

I'm going to keep an eye on this project, thanks for all your efforts!

**Comment by malc0mn** [comment]
Slipped my mind in my initial message, but I made a script to enumerate all PTP/IP ~~commands~~ device properties on my Fuji X-T1 camera, the output of which can be found here: https://github.com/malc0mn/ptp-ip/blob/master/docs/fuji_x-t1_known-properties.md

**Comment by petabyt** [comment]
Thanks for sharing! The only commands I've reverse engineered are the commnds used to write files and folders to SD card:
https://github.com/fujihack/fujihack/blob/master/ptp/fuji.py#L9
I have a XF1 from 2012, so I think most of the stuff from your project would be incompatible with mine. Though I haven't looked into vendor specific PTP properties, I think there were 2 I never figured out.
I think I recognize some of those constants though, I'll definitely keep it in mind when reverse engineering.
