### ISSUE TITLE
I am a user of XT20. I am very excited to see your project. If you can use CN filter on XT20, I will be very grateful. Thank you

### ISSUE THREAD

**Issue by cofooo** [fujihack/fujihack#17]
I am a user of XT20. I am very excited to see your project. If you can use CN filter on XT20, I will be very grateful. Thank you

**Comment by petabyt** [comment]
What is cn filter?

**Comment by petabyt** [comment]
Please don't spam.

**Comment by cofooo** [comment]
“Classic negative film”
I'm so sorry that my English is not pretty well
I'm not a native English speaker

**Comment by petabyt** [comment]
I'm not working on the project now so I won't do anything, but I think the custom debugger firmware is compiling for xt20 I think.

**Comment by cofooo** [comment]
Maybe the operating system with CN film can be installed on the model that does not support CN film in the future？

**Comment by petabyt** [comment]
Not sure what you're asking, ask a photography forum maybe
