### ISSUE TITLE
Display screen squeeze

### ISSUE THREAD

**Issue by docop** [fujihack/fujihack#18]
Hi  
Your projet is quite great.. while the doom port is great.. perhaps an easy fix can be added. If you put any like anamorphic or those kind of lens or filter, over multiple fuji cam, like the X-T200 , the whole screen appear 'compress.' And it's impossible to focus or properly see. The only way is to adjust in post.. after.
  On the high model xt-3 xt-4 they have a letterbox function. So indeed a letterbox function can be optimal, but, a super fast addition /mod can be just to apply a squeeze the horizontal display or viewfinder by 1.5. Not changing the saving file, but just the main display.
 That can be uber handy !

thanks in advance

**Comment by petabyt** [comment]
I really need to have a place to jot down feature requests like this.

**Comment by docop** [comment]
Oh.. yeah i understand. But at least, this one, is just refering to the display.. and not too deep.. i hope.. Anyhow, great finding super work !

**Comment by petabyt** [comment]
Added to a Trello list
