### ISSUE TITLE
Gyroscope

### ISSUE THREAD

**Issue by ziiw** [fujihack/fujihack#19]
Hello ! First, thanks for this awesome work you've work on this couple of years :) 

I did not have the chance to flash my xt3 yet. I was wondering if you think it will be possible to record the gyro data alongside the video recording.

I would like to use Gyroflow to stab the recordings on my camera ;)

Best,

**Comment by petabyt** [comment]
That would be a really cool idea :)
But to be honest it would be a lot easier to just attach another gyroscope to the camera (sounds like that might already exist?)
and match that to the timestamps of recorded videos.

**Comment by ziiw** [comment]
> That would be a really cool idea :) But to be honest it would be a lot easier to just attach another gyroscope to the camera (sounds like that might already exist?) and match that to the timestamps of recorded videos.

Thanks for the reply :) 

Indeed I saw some "Gyro Loggers" devices. I was concerned about the matching timestamps, not sure how to easily make them synchronised. Maybe with a clap movement at the beggining to see a big spike in the data logger and in the video.
