### ISSUE TITLE
"Corrupted" region in firmware file

### ISSUE THREAD

**Issue by sdroamt0** [fujihack/fujihack#2]
it's possible that in order to rightly unpack you should do some other checksum? for example, I download x-t10 firmware update from fujifilm and did try to unpack.

reading the unpacked version I find something like `A:\DCAA\auto_act.sc<91>` instead of `A:\DCAA\auto_act.scr` (<91> means 0x91 code) and also some other strings seems a bit corrupted...

Any hint?

**Comment by petabyt** [comment]
It does seem like it is corrupted.
I noticed the same thing with the X-T4 firmware. Some strings in one area look perfect, while
others look messed up.

Even after 0x91, there isn't a null terminator. I guess this suggests it is compressed?

**Comment by petabyt** [comment]
I do see some pattern. Lots of strings tend to end in 0x8X (X as in any number 0-f), rather than 0x0.
Also, running `binwalk` on output doesn't seem to find anything.

**Comment by petabyt** [comment]
Looks like everything before offset `0x007f89b8` seems to be compressed.
Everything after that seems to be valid strings and code.

**Comment by petabyt** [comment]
Looks like this section is visible in binvis.
![FWUP0007](https://user-images.githubusercontent.com/32369330/127906770-c625f054-d34b-4999-b41c-d4a2b19b8f6f.png)

**Comment by sdroamt0** [comment]
> It does seem like it is corrupted.
> I noticed the same thing with the X-T4 firmware. Some strings in one area look perfect, while
> others look messed up.
> 
> Even after 0x91, there isn't a null terminator. I guess this suggests it is compressed?

it could be, even if I always thought that (at least for the X series firmware) it was some periodic embedded checksum...I don't know... maybe to check at the size of the writable flash-memory pages but I never invested a lot of time to understand exactly

**Comment by petabyt** [comment]
Update: I compared two samples in the "corrupted" region of firmware and RAM dump, and it appears that the "corrupted" region is 40% smaller than the region in the RAM dump. This seems to confirm my compression idea.

**Comment by petabyt** [comment]
I dumped the region in a file, and ran `binwalk` on it. It couldn't find any recognizable compression format.

**Comment by petabyt** [comment]
I've got this mostly figured out (a section of firmware is decompressed on boot time, by the firmware)
