### ISSUE TITLE
Shutter Button issue in the FujiFilm FinePix A350 

### ISSUE THREAD

**Issue by f24x** [fujihack/fujihack#20]
So, the shutter button only works until halfway; it presses all the way down, but it only focuses and doesn't take any pictures. Is there a way I can change the code so that when I press the shutter button (till halfway) and the menu button at the same time, I'll take a picture? 

The Video's (the issue I'm facing) Link:
https://drive.google.com/file/d/1uaP7q-vFrP8MzRv4CTNFT6dv480PN29D/view?usp=drivesdk

**Comment by petabyt** [comment]
This hack doesn't work on cameras that old. Sorry but you're better off soldering a fake button onto it. Or just get a new camera.
