### ISSUE TITLE
Future Plans

### ISSUE THREAD

**Issue by petabyt** [fujihack/fujihack#6]
- [x] Decide on a Repository name: (Fujihack,Hackff, ffmod?). suggestions welcome, "Fujifilm" is reserved
- [ ] Register domain for project (fujihack.dev, fujihack.fm)
- [ ] Create Open Collective? (legal entity)
- [x] Complete the firmware utiluty (firm.c). Currently arguments are passed via preprocessor macros, should be via CLI arguments
- [x] Collect all existing publicly available information on Fujifilm camera internals in one place. (thorough Google research)
- [x] Create Wiki or website with information for newcomers
- [x] Fully Reverse engineer Fujifilm PTP/USB commands
- [x] RAM dump
- [x] Tetris port, or something to demonstrate stability
- [x] ROM dump
- [ ] bootloader ROM dump
- [ ] Extend 30 minute record limit (most likely a single byte change)
- [ ] Error bypassing (figured out how to beep/light LED, still confusing)
- [ ] Configure HDMI output
- [x] Phase out unmaintained `firm.c` utility in favor of web patcher
- [ ] Record 10 bit RAW video in MLV format
- [ ] Interface with WiFi web server (new cams, don't have one)

**Comment by deanc** [comment]
Interesting work. SWENG here with pretty much no experience in firmware hacking, but i'm curious if your journey is going to take you as far as patching features? There's a few things missing for example from X100F that they "fixed" in X100V that would be huge beneficial for productivity (e.g. presets including white balance settings)

**Comment by petabyt** [comment]
I'm sure it wouldn't be that hard to make small patches for a custom firmware, but I would say it's too dangerous for the average person. It could easily brick the camera. Currently I think our best bet is PTP/USB. I haven't figured out that much, (see the research file [here](https://github.com/petabyt/fujifilm/blob/master/ptp/research.py)), but I think there might be a lot to be discovered.

**Comment by dieideeistgut** [comment]
Hello there. Interesting reads. I'd like to suggest an addition to the list. For quite some users it may be interesting to simply downgrade the firmware to a previous version. I.e. for the X-Pro1 or older Models. From what i read in your findings this should be finally doable ( with the limitation of being forced to "upgrade" with a modified file lateron ).
Some years ago i was reading bit into this and there was a rumour (ha-ha) that there was a "reset"-firmware somewhere -  setting the internal version number to zero/nothing, allowing any version upgrade after. 
Thanks for the work!

**Comment by petabyt** [comment]
I never really thought about downgrading. Looks like Fujifilm doesn't host old firmware files, so it would be hard to get them unless they were archived.

> with the limitation of being forced to "upgrade" with a modified file lateron

I think this might actually not have to happen. The firmware version in the header is solely there to make sure the user can't downgrade or reinstall the same verison. The actual number that is written to the device seems to be stored somewhere else in the firmware.

**Comment by petabyt** [comment]
Unchecking project name, still open to new ideas.  
"Fuji" isn't reserved or anything, right?

**Comment by malc0mn** [comment]
Why not call it **Nuji**, but might be too far fetched, as a contraction of:
- Nu as in "new" (like back in the day for music genres: https://www.urbandictionary.com/define.php?term=nu-)
- Fuji, that's ... obvious...
🤷

**Edit**: maybe don't https://www.urbandictionary.com/define.php?term=Nuji 🫤

**Comment by petabyt** [comment]
Looks like Nuji is a clothing company? I think very short names or made up names tend to get confused a lot, like CHDK: https://www.youtube.com/watch?v=7FMGLjtHh-I&t=107s
Also it's taken on github :( https://github.com/nuji

**Comment by cofooo** [comment]
我是XT20的用户。我很高兴看到你的项目。如果您能在XT20上使用Classic negative过滤器，我将不胜感激。谢谢您

**Comment by cofooo** [comment]
I am a user of XT20. I am very excited to see your project. If you can use Classic negative filter on XT20, I will be very grateful. Thank you

**Comment by petabyt** [comment]
Fujihack is probably fine, "fuji" is not trademarked by Fujiflim https://tmsearch.uspto.gov/bin/gate.exe?f=tess&state=4803:kn7x35.6.50
