### ISSUE TITLE
Adding a particular Feature to the XPro Line of cameras

### ISSUE THREAD

**Issue by niklasarnitz** [fujihack/fujihack#7]
Hi, I have been working on reversing the Fuji cameras to add a "XPan" like shooting mode to my XPro cameras (Have the XPro1 and XPro3) which just shoots panoramically cropped images and shows the correct framelines in the viewfinder.

How much reworking do you think would need to be done?

**Comment by petabyt** [comment]
Sounds like a lot, especially if you are wanting to change the entire image saving process. Right now, a good goal for this project would be trying to disable the 30 minute video limit, and maybe adding some basic overlays.
