### ISSUE TITLE
Resetting firmware

### ISSUE THREAD

**Issue by ghost** [fujihack/fujihack#9]
I saw the warnings on the README but I wanted to triple check: does utilizing this risk that you brick the camera or is there a way for me to wipe the camera and start from scratch.

**Comment by petabyt** [comment]
Not that I know of. Canon cameras have something like this - where you can execute autoexec.bin files even if the ROM is messed up.

I did find a button combination in a service manual that *seemed* to open the bootloader (shows a green LED, nothing on screen), with ability to send code through USB. I haven't figured out how that works yet.

Even if there was a way to recover the camera after being firmware bricked, I still wouldn't want anybody to flash a custom firmware, especially on a $200+ camera.
